In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
import numpy as np
arr=np.zeros((10,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
import numpy as np
arr=np.zeros((10,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [13]:
import numpy as np
arr=np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [14]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
import numpy as np
arr=np.arange(1,100,)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [25]:
import numpy as np
arr=np.arange(3,200,2)
print(arr)


[  3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37
  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73
  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109
 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143 145
 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181
 183 185 187 189 191 193 195 197 199]


In [28]:
import numpy as np
arr =np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [30]:
import numpy as np
arr=np.random.rand(20)
print(arr)

[0.83357897 0.60193063 0.8611577  0.25736072 0.56719014 0.62488452
 0.79197065 0.96577531 0.55502128 0.57359277 0.62236673 0.7748014
 0.7496156  0.78879778 0.58982219 0.41777779 0.13385318 0.22869122
 0.75917189 0.27695106]


In [32]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[-0.84736614 -2.09284367 -1.15258621 -1.41413139 -0.13388656  0.49355704
 -0.68268643  1.60010748  1.69466072 -1.26733968]


In [50]:
import numpy as np
arr=np.random.randint(200)
print(arr)

102


In [56]:
import numpy as np
colours=["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))

['black' 'white']


In [58]:
#copy
import numpy as np

arr=np.array([1,2,3])
new=arr.copy()
new[1]=200
print("array value is:",arr)
print("copy value is:",new)

array value is: [1 2 3]
copy value is: [  1 200   3]


In [59]:
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[1]=100
print("array value is:",arr)
print("new value is:",new)

array value is: [  1 100   3]
new value is: [  1 100   3]


In [60]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr+=10
print("updated array value is :",arr)

updated array value is : [15 20 25 30 35 40]


In [66]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [67]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))

130


In [76]:
import numpy as np
arr=np.array([1,2,3,4,100,100,6,7,8,9])
print(sum(arr))
print(np.std(arr))
print(np.sqrt(arr))
print(np.max(arr))
print(np.min(arr))
print(np.average(arr))
print(np.median(arr))
print(np.sort(arr))
print(np.unique(arr))

240
38.07886552931954
[ 1.          1.41421356  1.73205081  2.         10.         10.
  2.44948974  2.64575131  2.82842712  3.        ]
100
1
24.0
6.5
[  1   2   3   4   6   7   8   9 100 100]
[  1   2   3   4   6   7   8   9 100]


In [85]:
import numpy as np
arr=np.array([1,2,3,4,100,100,6,7,8,9])
print(np.shape(arr))
print(np.size(arr))
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)

(10,)
10
8
1
int64


In [94]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[:,1])

(2, 4)
2
2
[2 6]


In [101]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("original array",arr)
new=arr.reshape(3,3)
print(new)

original array [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
